spring:
  application:
    name: gateway-service

server:
  port: 8700

eureka:
  client:
    registerWithEureka: false
    fetch-registry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka/

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
